#!/usr/bin/env python3
"""
Generate ~115 QSOs each into the starter DEQP test log files. Deterministic
via a fixed RNG seed so the produced logs are stable across re-runs and
across contributors verifying scoring changes. Inserts a small number of
duplicates per log to validate the engine's per-band/mode dupe detection.

Reads:  test_logs/test_deqp_instate.clx     (DE station, KX9DE from SDE — Sussex)
        test_logs/test_deqp_outofstate.clx  (FL station, N9OH operator)
Writes: same files, with the existing starter QSOs preserved and new
        synthesized QSOs appended.

Usage:  python3 scripts/generate_deqp_test_logs.py [--seed 13]
"""

import argparse
import json
import os
import random
from datetime import datetime, timedelta, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTEST_FILE = os.path.join(REPO_ROOT, "contests", "deqp.json")
INSTATE_LOG  = os.path.join(REPO_ROOT, "test_logs", "test_deqp_instate.clx")
OOS_LOG      = os.path.join(REPO_ROOT, "test_logs", "test_deqp_outofstate.clx")

# Three Delaware county codes — every DE station's exchange.
DE_COUNTIES = ["NDE", "KDE", "SDE"]

# Non-DE US states a station might send. DE itself is excluded — DE ops
# don't see "DE" 2-letter from anyone; non-DE ops only work DE.
NON_DE_US_STATES = [
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "FL", "GA",
    "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
    "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
    "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
]

PROVINCES = ["NS", "QC", "ON", "MB", "SK", "AB", "BC", "NT", "NB", "NL", "NU", "YT", "PE"]

BAND_FREQ_PRESETS = {
    "160m": {"CW": 1825, "SSB": 1860, "DIGITAL": 1830},
    "80m":  {"CW": 3550, "SSB": 3960, "DIGITAL": 3580},
    "40m":  {"CW": 7050, "SSB": 7260, "DIGITAL": 7080},
    "20m":  {"CW": 14050, "SSB": 14280, "DIGITAL": 14080},
    "15m":  {"CW": 21050, "SSB": 21360, "DIGITAL": 21080},
    "10m":  {"CW": 28050, "SSB": 28360, "DIGITAL": 28080},
}

def ssb_mode_for_band(band):
    return "LSB" if band in ("160m", "80m", "40m") else "USB"

# Mode → band weighting matched to typical DEQP activity. 20/40m carry
# most of the action; 160m is sparse.
BAND_WEIGHTS_BY_MODE = {
    "CW":      {"160m": 4,  "80m": 14, "40m": 30, "20m": 33, "15m": 14, "10m": 5},
    "SSB":     {"160m": 2,  "80m": 12, "40m": 28, "20m": 35, "15m": 17, "10m": 6},
    "DIGITAL": {"160m": 0,  "80m": 6,  "40m": 26, "20m": 48, "15m": 14, "10m": 6},
}

# Mode mix target — DEQP allows CW/SSB/DIGITAL (RTTY/PSK; FT8/FT4 logged
# separately in WSJT-X). Realistic split for a state QSO party:
MODE_MIX_TARGET = {"CW": 45, "SSB": 50, "DIGITAL": 5}

US_PREFIXES_SINGLE = ["W", "K", "N"]
US_PREFIXES_DOUBLE = ["AA", "AB", "AC", "AD", "AE", "AF", "AG", "AI", "AJ", "AK",
                       "KA", "KB", "KC", "KD", "KE", "KF", "KG", "KI", "KJ", "KK",
                       "KM", "KN", "KO", "NA", "NB", "NC", "ND", "NE", "NF", "NG",
                       "NI", "NJ", "NK", "NN", "NO", "WA", "WB", "WD", "WE", "WF",
                       "WG", "WI", "WJ", "WK", "WM", "WN", "WO"]

CANADIAN_PREFIXES = {
    "NS": ["VE1", "VA1"], "QC": ["VE2", "VA2"], "ON": ["VE3", "VA3"],
    "MB": ["VE4", "VA4"], "SK": ["VE5", "VA5"], "AB": ["VE6", "VA6"],
    "BC": ["VE7", "VA7"], "NT": ["VE8", "VA8"], "NB": ["VE9", "VA9"],
    "NL": ["VO1", "VO2"], "PE": ["VY2"], "YT": ["VY1"], "NU": ["VY0"],
}

DX_PREFIXES = ["G", "DL", "F", "I", "JA", "EA", "PA", "OE", "OH", "SM",
               "OZ", "OK", "9A", "S5", "SP", "HB9", "LA", "EI", "GW",
               "ZL", "VK", "ZS", "PY", "LU", "CE", "XE", "TI", "HK"]

# DE call area is 3 (W3, K3, N3 etc.). DE state operators almost always
# use a digit-3 call.
STATE_TO_AREA_DIGIT = {
    "CT": "1", "ME": "1", "MA": "1", "NH": "1", "RI": "1", "VT": "1",
    "NY": "2", "NJ": "2",
    "MD": "3", "PA": "3", "DC": "3",  # DE excluded — generated by gen_de_call
    "AL": "4", "FL": "4", "GA": "4", "KY": "4", "NC": "4", "SC": "4",
    "TN": "4", "VA": "4",
    "AR": "5", "LA": "5", "MS": "5", "NM": "5", "OK": "5", "TX": "5",
    "CA": "6",
    "AZ": "7", "ID": "7", "MT": "7", "NV": "7", "OR": "7", "UT": "7",
    "WA": "7", "WY": "7",
    "MI": "8", "OH": "8", "WV": "8",
    "IL": "9", "IN": "9", "WI": "9",
    "CO": "0", "IA": "0", "KS": "0", "MN": "0", "MO": "0", "NE": "0",
    "ND": "0", "SD": "0",
    "AK": "L", "HI": "H",
}

def gen_us_call_with_digit(rng, digit):
    if rng.random() < 0.7:
        prefix = rng.choice(US_PREFIXES_SINGLE)
    else:
        prefix = rng.choice(US_PREFIXES_DOUBLE)
    suffix_len = rng.choices([1, 2, 3], weights=[5, 50, 45])[0]
    suffix = "".join(rng.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=suffix_len))
    return f"{prefix}{digit}{suffix}"

def gen_call_for_us_state(rng, state):
    if state == "AK":
        return f"KL7{''.join(rng.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ', k=rng.choice([2, 3])))}"
    if state == "HI":
        return f"KH6{''.join(rng.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ', k=rng.choice([2, 3])))}"
    digit = STATE_TO_AREA_DIGIT.get(state, "0")
    return gen_us_call_with_digit(rng, digit)

def gen_de_call(rng):
    """Delaware stations almost always use W3/K3/N3 calls."""
    return gen_us_call_with_digit(rng, "3")

def gen_canadian_call(rng, province):
    prefix = rng.choice(CANADIAN_PREFIXES[province])
    suffix_len = rng.choices([2, 3], weights=[60, 40])[0]
    suffix = "".join(rng.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=suffix_len))
    return f"{prefix}{suffix}"

def gen_dx_call(rng):
    prefix = rng.choice(DX_PREFIXES)
    digit = str(rng.randint(0, 9))
    suffix_len = rng.choices([2, 3], weights=[55, 45])[0]
    suffix = "".join(rng.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=suffix_len))
    return f"{prefix}{digit}{suffix}"

def pick_mode(rng):
    return rng.choices(list(MODE_MIX_TARGET.keys()),
                       weights=list(MODE_MIX_TARGET.values()))[0]

def pick_band_for_mode(rng, mode):
    weights = BAND_WEIGHTS_BY_MODE[mode]
    bands = list(weights.keys())
    return rng.choices(bands, weights=[weights[b] for b in bands])[0]

def cw_or_ssb_log_mode(mode, band):
    if mode == "CW":
        return "CW"
    if mode == "SSB":
        return ssb_mode_for_band(band)
    if mode == "DIGITAL":
        return "RTTY"
    return mode

def make_qso(qso_id, ts, callsign, band, mode_log, freq, exch_recvd, exch_sent, rst_set, duplicate=False):
    rst_s, rst_r = rst_set
    return {
        "band": band,
        "callsign": callsign,
        "duplicate": duplicate,
        "dxcc_count": 0,
        "exchange_fields": {
            "CALL":  callsign,
            "EXCHr": exch_recvd,
            "EXCHs": exch_sent,
            "NAMEs": "Steve",
            "RSTr":  rst_r,
            "RSTs":  rst_s,
            "SNs":   str(qso_id),
        },
        "frequency": freq,
        "grid_square_count": 0,
        "id": qso_id,
        "mode": mode_log,
        "multiplier_count": 0,
        "points":           0,
        "rst_received": rst_r,
        "rst_sent":     rst_s,
        "serial": qso_id,
        "timestamp": ts.strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

def rst_for_mode(mode):
    return ("599", "599") if mode in ("CW", "DIGITAL") else ("59", "59")

def insert_dupes(qsos, rng, count, next_id_start):
    """Append `count` per-band/mode duplicates against existing non-dupe QSOs."""
    out = []
    next_id = next_id_start
    candidates = [q for q in qsos if not q.get("duplicate", False)]
    for _ in range(count):
        original = rng.choice(candidates)
        orig_ts = datetime.fromisoformat(original["timestamp"].replace("Z", "+00:00"))
        dupe_ts = orig_ts + timedelta(seconds=rng.randint(60, 240))
        dupe = make_qso(
            qso_id=next_id,
            ts=dupe_ts,
            callsign=original["callsign"],
            band=original["band"],
            mode_log=original["mode"],
            freq=original["frequency"],
            exch_recvd=original["exchange_fields"]["EXCHr"],
            exch_sent=original["exchange_fields"]["EXCHs"],
            rst_set=(original["rst_sent"], original["rst_received"]),
            duplicate=True,
        )
        out.append(dupe)
        next_id += 1
    return out

def gen_qsos_for_instate(starter, rng, target_total=115, dupe_count=3):
    """KX9DE from Sussex (SDE) works EVERYONE. Rules: DE-DE QSOs earn point
    credit but NO multiplier credit (DE op's namedMults excludes county
    codes by design). DX QSOs earn 1/2/2 points and DXCC entity credit.

    Mix:
      ~20% other DE stations (NDE/KDE/SDE — points only, no mult — exercises
            the DE-DE no-mult path),
      ~45% non-DE US (2-letter state — the bulk of mults),
      ~15% Canadian (2-letter province),
      ~20% DX (gets DXCC mult credit since DE ops include the dxcc category).
    """
    out = []
    next_id = starter["qsos"][-1]["id"] + 1
    last_ts = datetime.fromisoformat(starter["qsos"][-1]["timestamp"].replace("Z", "+00:00"))
    used_keys = set()
    for q in starter["qsos"]:
        used_keys.add((q["callsign"], q["band"],
                       "SSB" if q["mode"] in ("USB", "LSB") else
                       ("DIGITAL" if q["mode"] in ("RTTY", "PSK") else q["mode"])))

    needed_real = target_total - len(starter["qsos"]) - dupe_count
    operator_exch_sent = "SDE"  # Sussex County

    for _ in range(needed_real):
        # DEQP runs ~24 hours; ~115 QSOs over 24h = avg 12.5 minutes apart.
        last_ts = last_ts + timedelta(seconds=rng.randint(180, 900))
        mode = pick_mode(rng)
        band = pick_band_for_mode(rng, mode)
        log_mode = cw_or_ssb_log_mode(mode, band)
        freq = BAND_FREQ_PRESETS[band][mode]

        cat_roll = rng.random()
        if cat_roll < 0.20:
            # Other DE station — points only, no mult (DE op's namedMults
            # doesn't contain NDE/KDE/SDE so engine naturally skips).
            exch_r = rng.choice(DE_COUNTIES)
            call = gen_de_call(rng)
        elif cat_roll < 0.65:
            their_state = rng.choice(NON_DE_US_STATES)
            exch_r = their_state
            call = gen_call_for_us_state(rng, their_state)
        elif cat_roll < 0.80:
            province = rng.choice(PROVINCES)
            exch_r = province
            call = gen_canadian_call(rng, province)
        else:
            # DX — earns points AND DXCC entity mult per band (multsPerBand).
            exch_r = "DX"
            call = gen_dx_call(rng)

        # Avoid per-band/mode dupes from random reuse
        for _ in range(20):
            if (call, band, mode) not in used_keys:
                break
            if exch_r == "DX":
                call = gen_dx_call(rng)
            elif exch_r in DE_COUNTIES:
                call = gen_de_call(rng)
            elif exch_r in PROVINCES:
                call = gen_canadian_call(rng, exch_r)
            else:
                call = gen_call_for_us_state(rng, exch_r)
        used_keys.add((call, band, mode))

        rst_set = rst_for_mode(mode)
        out.append(make_qso(next_id, last_ts, call, band, log_mode, freq,
                            exch_r, operator_exch_sent, rst_set))
        next_id += 1

    out += insert_dupes(out + starter["qsos"], rng, dupe_count, next_id)
    return out

def gen_qsos_for_outofstate(starter, rng, target_total=115, dupe_count=2):
    """N9OH (FL) works only DE. Every received exchange is one of the 3
    DE county codes; calls are W3/K3/N3 area-3 calls."""
    out = []
    next_id = starter["qsos"][-1]["id"] + 1
    last_ts = datetime.fromisoformat(starter["qsos"][-1]["timestamp"].replace("Z", "+00:00"))
    used_keys = set()
    for q in starter["qsos"]:
        used_keys.add((q["callsign"], q["band"],
                       "SSB" if q["mode"] in ("USB", "LSB") else
                       ("DIGITAL" if q["mode"] in ("RTTY", "PSK") else q["mode"])))

    needed_real = target_total - len(starter["qsos"]) - dupe_count
    operator_exch_sent = "FL"

    for _ in range(needed_real):
        last_ts = last_ts + timedelta(seconds=rng.randint(180, 900))
        mode = pick_mode(rng)
        band = pick_band_for_mode(rng, mode)
        log_mode = cw_or_ssb_log_mode(mode, band)
        freq = BAND_FREQ_PRESETS[band][mode]

        exch_r = rng.choice(DE_COUNTIES)
        call = gen_de_call(rng)

        for _ in range(20):
            if (call, band, mode) not in used_keys:
                break
            call = gen_de_call(rng)
        used_keys.add((call, band, mode))

        rst_set = rst_for_mode(mode)
        out.append(make_qso(next_id, last_ts, call, band, log_mode, freq,
                            exch_r, operator_exch_sent, rst_set))
        next_id += 1

    out += insert_dupes(out + starter["qsos"], rng, dupe_count, next_id)
    return out

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=13,
                        help="RNG seed for reproducible output (default 13)")
    parser.add_argument("--total", type=int, default=115,
                        help="Target total QSOs per file (default 115)")
    args = parser.parse_args()

    for path, gen_fn, label, default_dupes in [
        (INSTATE_LOG, gen_qsos_for_instate,    "in-state (DE)",     3),
        (OOS_LOG,     gen_qsos_for_outofstate, "out-of-state (FL)", 2),
    ]:
        with open(path, "r") as f:
            log = json.load(f)
        rng = random.Random(args.seed)
        # Seed the dupe count with the RNG too — same seed gives same
        # count, but different logs get different counts.
        actual_dupes = rng.choice([1, 2, 3, 4]) if default_dupes else 0
        # Restore-then-burn: restore the RNG state before generating QSOs
        # so the dupe-count draw doesn't shift downstream randomness. Use
        # a fresh RNG seeded the same way to keep the QSO sequence stable
        # across changes to dupe-count logic.
        rng = random.Random(args.seed)
        new_qsos = gen_fn(log, rng, target_total=args.total,
                          dupe_count=actual_dupes)
        log["qsos"].extend(new_qsos)
        log["statistics"] = {
            "score": 0,
            "total_points": 0,
            "total_qsos": len(log["qsos"]),
        }
        log["modified"] = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
        with open(path, "w") as f:
            json.dump(log, f, indent=4)
            f.write("\n")
        print(f"{label}: now {len(log['qsos'])} QSOs ({len(new_qsos)} added, "
              f"{actual_dupes} flagged as duplicates) -> {path}")

if __name__ == "__main__":
    main()
