/*
 * ContestLogX - Amateur Radio Contest Logging Software
 * Copyright (c) 2025-2026 Steve Woodruff, N9OH
 *
 * Released under the MIT License. See LICENSE file for details.
 */

#ifndef WINKEYERCLIENT_H
#define WINKEYERCLIENT_H

#include <QObject>
#include <QThread>
#include <QMutex>
#include <QString>
#include "cwKeyerInterface.h"

class QSerialPort;
class WinKeyerWorker;

/**
 * @brief K1EL WinKeyer (and WinKey-protocol-compatible) CW keyer client.
 *
 * Talks the WinKey host protocol over a serial port. Framing defaults to the
 * classic 1200 8N1 (matching AtomKey) but baud and stop bits are caller-
 * supplied so a real USB WKmini that wants other values still works. Unlike the
 * rig backends this is a pure CW keyer (CwKeyerInterface, not RigInterface):
 * it does no frequency/mode control. Element timing is generated by the keyer
 * hardware, off the host PC and off the CAT channel - that is the whole point
 * of using it instead of flrig cwio.
 *
 * All serial I/O runs on a background thread (WinKeyerWorker), mirroring the
 * HamlibClient pattern: blocking open/close, fire-and-forget setters, and
 * status bytes surfaced via busyChanged().
 */
class WinKeyerClient : public QObject, public CwKeyerInterface
{
    Q_OBJECT

public:
    explicit WinKeyerClient(QObject *parent = nullptr);
    ~WinKeyerClient();

    // Open the serial port and run the WinKey host-open handshake. Returns true
    // only if the keyer answered with a revision byte. Blocking - use for a
    // deliberate user action (e.g. the Detect button), not on the UI path.
    bool openPort(const QString& portName, int baud = 1200, int stopBits = 1);
    // Non-blocking open: returns immediately; emits connected() or error() when
    // the handshake completes on the worker thread. Use for startup/config so
    // the UI never freezes on the boot-wait.
    void connectAsync(const QString& portName, int baud = 1200, int stopBits = 1);
    void closePort();

    // CwKeyerInterface
    bool isConnected() const override;
    bool sendCW(const QString& text) override;
    bool stopCW() override;
    int getCWSpeed() override;
    bool setCWSpeed(int wpm) override;
    bool supportsCW() const override { return true; }

    // Firmware revision byte from host-open (>= 0 when detected, -1 otherwise).
    int revision() const;
    QString portName() const;

signals:
    void connected();
    void disconnected();
    void error(const QString& errorString);
    // Driven by WinKey status bytes: true while the keyer is actively sending.
    void busyChanged(bool busy);

private:
    QThread m_workerThread;
    WinKeyerWorker *m_worker;
    mutable QMutex m_mutex;

    bool m_connected;
    int m_revision;
    int m_cachedWpm;
    QString m_portName;
};

/**
 * @brief Worker that owns the QSerialPort and runs on a background thread.
 */
class WinKeyerWorker : public QObject
{
    Q_OBJECT

public:
    explicit WinKeyerWorker(QObject *parent = nullptr);
    ~WinKeyerWorker();

    bool isConnected() const { return m_connected; }
    int revision() const { return m_revision; }

public slots:
    void doOpen(const QString& portName, int baud, int stopBits);
    void doClose();
    void doSendCW(const QString& text);
    void doStopCW();
    void doSetCWSpeed(int wpm);

signals:
    void openResult(bool success, int revision);
    void closed();
    void serialError(const QString& errorString);
    void busyChanged(bool busy);

private slots:
    void onReadyRead();

private:
    QSerialPort *m_serial;
    bool m_connected;
    int m_revision;
    bool m_lastBusy;
};

#endif // WINKEYERCLIENT_H
